package com.example.demo.enum

enum class CType {
    SINGLE_IMAGE,
    COLOR_BLOCK,
    GENERAL_TITLE,
    DIGITAL_CARD_FLIPPER,
    STACKED_COLUMN_CHART,
    BAR_WITH_BACKGROUND,
    MULTIPLE_X_AXES,
    BUS_LINE,
    DOUGHNUT_CHART_WITH_ROUNDED_CORNER,
    BUBBLE_CHART,
    FOLDER,
}